# Netlify Configuration File

[build]
  publish = "public"  # Change this if your site files are in a different directory
  command = ""  # Leave empty if not using a build process

# Redirect Rules
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Headers (Optional: Enable CORS for config.yml if needed)
[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "text/yaml"
