backend:
  name: github
  repo: LiveLightWebsite/LiveLight-Website  # Replace this with your correct GitHub repo name
  branch: main
  auth_scope: repo

media_library:
  name: uploadcare
  config:
    publicKey: demo  # Replace this with your actual Uploadcare API key if needed

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "settings"
        file: "settings.json"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }
